packages:
  - apps/*
  - packages/*
  - blockchain/contracts

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd

patchedDependencies:
  nitro-cloudflare-dev@0.2.2: patches/nitro-cloudflare-dev@0.2.2.patch
