-- Migration: 0003_campaigns_domain
-- Created: 2025-01-29
-- Description: Campaign domain schema - Core entity for pledge campaigns
-- Domain: Campaigns (Core Entity)

-- ============================================================================
-- CAMPAIGNS TABLE
-- Purpose: Stores all campaign metadata, verification data, and state
-- Design: Supports CRE/DECO consensus, staking/bonds, and full lifecycle
-- ============================================================================
CREATE TABLE IF NOT EXISTS campaigns (
    -- Primary key: UUID generated by application layer
    campaign_id TEXT PRIMARY KEY 
        CHECK (length(campaign_id) = 36),
    
    -- Creator's wallet address (foreign key to users)
    creator_address TEXT NOT NULL,
    
    -- Campaign identity
    name TEXT NOT NULL 
        CHECK (length(name) >= 3 AND length(name) <= 100),
    slug TEXT UNIQUE NOT NULL 
        CHECK (slug GLOB '[a-z0-9-]*' AND length(slug) >= 3 AND length(slug) <= 100),
    
    -- Campaign description and rules
    purpose TEXT NOT NULL 
        CHECK (length(purpose) >= 10 AND length(purpose) <= 1000),
    rules_and_resolution TEXT NOT NULL 
        CHECK (length(rules_and_resolution) >= 10 AND length(rules_and_resolution) <= 2000),
    
    -- AI verification prompt and hash
    prompt TEXT NOT NULL 
        CHECK (length(prompt) >= 20 AND length(prompt) <= 5000),
    prompt_hash TEXT NOT NULL,  -- keccak256 hash of prompt
    
    -- Campaign lifecycle status
    status TEXT NOT NULL DEFAULT 'draft' 
        CHECK (status IN ('draft', 'submitted', 'approved', 'active', 'complete', 'failed', 'disputed', 'cancelled')),
    
    -- Baseline verification data (DECO/ZKP proofs stored as JSON)
    baseline_data TEXT DEFAULT '{}',
    
    -- Privacy settings
    privacy_mode INTEGER DEFAULT 0,
    
    -- Consensus configuration
    consensus_threshold REAL DEFAULT 0.66 
        CHECK (consensus_threshold >= 0.5 AND consensus_threshold <= 1.0),
    
    -- Financial data (stored as TEXT for large numbers - wei values)
    creator_bond TEXT DEFAULT '0',
    amount_pledged TEXT DEFAULT '0',
    fundraising_goal TEXT NOT NULL 
        CHECK (CAST(fundraising_goal AS INTEGER) > 0),
    
    -- Yield/rewards configuration
    yield_rate REAL DEFAULT 0.0,
    yield_pool TEXT DEFAULT '0',
    
    -- Categorization (stored as JSON arrays)
    tags TEXT DEFAULT '[]',
    categories TEXT DEFAULT '[]',
    
    -- Media
    image_url TEXT,
    banner_url TEXT,
    
    -- Feature flags
    is_showcased INTEGER DEFAULT 0,
    is_featured INTEGER DEFAULT 0,
    is_verified INTEGER DEFAULT 0,
    
    -- History and consensus results (stored as JSON arrays)
    history TEXT DEFAULT '[]',
    consensus_results TEXT DEFAULT '[]',
    
    -- Dispute tracking
    is_disputed INTEGER DEFAULT 0,
    dispute_reason TEXT,
    dispute_resolution TEXT,
    
    -- Escrow contract address (set when campaign goes active)
    escrow_address TEXT,
    
    -- On-chain transaction references
    creation_tx_hash TEXT,
    activation_tx_hash TEXT,
    completion_tx_hash TEXT,
    
    -- Timeline
    start_date TEXT,
    end_date TEXT NOT NULL,
    
    -- Statistics (denormalized for performance)
    pledge_count INTEGER DEFAULT 0,
    unique_pledgers INTEGER DEFAULT 0,
    voucher_count INTEGER DEFAULT 0,
    disputer_count INTEGER DEFAULT 0,
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    submitted_at TEXT,
    approved_at TEXT,
    activated_at TEXT,
    completed_at TEXT,
    
    -- Soft delete
    is_deleted INTEGER DEFAULT 0,
    deleted_at TEXT,
    
    -- Foreign key constraint
    FOREIGN KEY (creator_address) REFERENCES users(address) ON DELETE RESTRICT
);

-- ============================================================================
-- INDEXES
-- Purpose: Optimize query performance for common access patterns
-- ============================================================================

-- Primary access patterns
CREATE INDEX IF NOT EXISTS idx_campaigns_creator ON campaigns(creator_address);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_campaigns_slug ON campaigns(slug);

-- Date-based queries
CREATE INDEX IF NOT EXISTS idx_campaigns_end_date ON campaigns(end_date);
CREATE INDEX IF NOT EXISTS idx_campaigns_created_at ON campaigns(created_at DESC);

-- Featured/showcased campaigns
CREATE INDEX IF NOT EXISTS idx_campaigns_showcased ON campaigns(is_showcased, status);
CREATE INDEX IF NOT EXISTS idx_campaigns_featured ON campaigns(is_featured, status);

-- Active campaigns filter (common query)
CREATE INDEX IF NOT EXISTS idx_campaigns_active ON campaigns(status, end_date) 
    WHERE status = 'active' AND is_deleted = 0;

-- Disputed campaigns
CREATE INDEX IF NOT EXISTS idx_campaigns_disputed ON campaigns(is_disputed, status);

-- Composite: Status + Creator for user dashboards
CREATE INDEX IF NOT EXISTS idx_campaigns_creator_status ON campaigns(creator_address, status);

-- Amount pledged for sorting by popularity
CREATE INDEX IF NOT EXISTS idx_campaigns_pledged ON campaigns(amount_pledged DESC);

-- ============================================================================
-- TRIGGERS
-- Purpose: Maintain data integrity and audit trail
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS trg_campaigns_updated_at
AFTER UPDATE ON campaigns
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE campaigns SET updated_at = datetime('now') WHERE campaign_id = NEW.campaign_id;
END;

-- Track status transitions in history
CREATE TRIGGER IF NOT EXISTS trg_campaigns_status_change
AFTER UPDATE OF status ON campaigns
FOR EACH ROW
WHEN NEW.status != OLD.status
BEGIN
    UPDATE campaigns 
    SET history = json_insert(
        history, 
        '$[#]', 
        json_object(
            'timestamp', datetime('now'),
            'action', 'status_change',
            'from_status', OLD.status,
            'to_status', NEW.status
        )
    )
    WHERE campaign_id = NEW.campaign_id;
END;
