-- Migration: 0004_pledges_domain
-- Created: 2025-01-29
-- Description: Pledge domain schema - Individual pledges to campaigns
-- Domain: Pledges

-- ============================================================================
-- PLEDGES TABLE
-- Purpose: Tracks individual pledges made to campaigns
-- Design: Full transaction tracking with on-chain reference
-- ============================================================================
CREATE TABLE IF NOT EXISTS pledges (
    -- Primary key: UUID generated by application layer
    pledge_id TEXT PRIMARY KEY 
        CHECK (length(pledge_id) = 36),
    
    -- Foreign key to campaign
    campaign_id TEXT NOT NULL,
    
    -- Pledger's wallet address (foreign key to users)
    pledger_address TEXT NOT NULL,
    
    -- Pledge amount (in wei, stored as TEXT for large numbers)
    amount TEXT NOT NULL 
        CHECK (CAST(amount AS INTEGER) > 0),
    
    -- Optional pledge message/note
    message TEXT 
        CHECK (message IS NULL OR length(message) <= 280),
    
    -- Pledge lifecycle status
    status TEXT NOT NULL DEFAULT 'pending' 
        CHECK (status IN ('pending', 'confirmed', 'active', 'released', 'refunded', 'failed')),
    
    -- On-chain transaction reference
    tx_hash TEXT NOT NULL,
    block_number INTEGER,
    block_timestamp TEXT,
    
    -- Confirmation tracking
    confirmations INTEGER DEFAULT 0,
    confirmed_at TEXT,
    
    -- Release/refund tracking
    release_tx_hash TEXT,
    refund_tx_hash TEXT,
    released_at TEXT,
    refunded_at TEXT,
    
    -- Yield tracking (if applicable)
    yield_earned TEXT DEFAULT '0',
    yield_claimed TEXT DEFAULT '0',
    last_yield_claim_at TEXT,
    
    -- Anonymous pledge flag
    is_anonymous INTEGER DEFAULT 0,
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    pledged_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Foreign key constraints
    FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
    FOREIGN KEY (pledger_address) REFERENCES users(address) ON DELETE RESTRICT
);

-- ============================================================================
-- INDEXES
-- Purpose: Optimize query performance for common access patterns
-- ============================================================================

-- Primary access patterns
CREATE INDEX IF NOT EXISTS idx_pledges_campaign ON pledges(campaign_id);
CREATE INDEX IF NOT EXISTS idx_pledges_pledger ON pledges(pledger_address);
CREATE INDEX IF NOT EXISTS idx_pledges_status ON pledges(status);

-- Transaction lookup
CREATE INDEX IF NOT EXISTS idx_pledges_tx_hash ON pledges(tx_hash);

-- Date-based queries
CREATE INDEX IF NOT EXISTS idx_pledges_created_at ON pledges(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pledges_pledged_at ON pledges(pledged_at DESC);

-- Composite: Campaign + Status for campaign stats
CREATE INDEX IF NOT EXISTS idx_pledges_campaign_status ON pledges(campaign_id, status);

-- Composite: Pledger + Status for user dashboards
CREATE INDEX IF NOT EXISTS idx_pledges_pledger_status ON pledges(pledger_address, status);

-- Active pledges for a campaign
CREATE INDEX IF NOT EXISTS idx_pledges_campaign_active ON pledges(campaign_id, amount) 
    WHERE status IN ('confirmed', 'active');

-- ============================================================================
-- TRIGGERS
-- Purpose: Maintain data integrity and audit trail
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS trg_pledges_updated_at
AFTER UPDATE ON pledges
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE pledges SET updated_at = datetime('now') WHERE pledge_id = NEW.pledge_id;
END;

-- Update campaign pledge count on new pledge
CREATE TRIGGER IF NOT EXISTS trg_pledges_increment_count
AFTER INSERT ON pledges
FOR EACH ROW
WHEN NEW.status IN ('confirmed', 'active')
BEGIN
    UPDATE campaigns 
    SET 
        pledge_count = pledge_count + 1,
        amount_pledged = CAST(CAST(amount_pledged AS INTEGER) + CAST(NEW.amount AS INTEGER) AS TEXT),
        updated_at = datetime('now')
    WHERE campaign_id = NEW.campaign_id;
END;
