-- Migration: 0005_vouchers_domain
-- Created: 2025-01-29
-- Description: Vouchers (Endorsers) domain schema
-- Domain: Vouchers/Endorsers

-- ============================================================================
-- VOUCHERS TABLE
-- Purpose: Tracks endorsers who stake funds to vouch for campaign legitimacy
-- Design: Staking mechanism for campaign verification/reputation
-- ============================================================================
CREATE TABLE IF NOT EXISTS vouchers (
    -- Primary key: UUID generated by application layer
    voucher_id TEXT PRIMARY KEY 
        CHECK (length(voucher_id) = 36),
    
    -- Foreign key to campaign
    campaign_id TEXT NOT NULL,
    
    -- Voucher's wallet address (foreign key to users)
    voucher_address TEXT NOT NULL,
    
    -- Staked amount (in wei, stored as TEXT for large numbers)
    amount TEXT NOT NULL 
        CHECK (CAST(amount AS INTEGER) > 0),
    
    -- Vouching status
    status TEXT NOT NULL DEFAULT 'active' 
        CHECK (status IN ('pending', 'active', 'released', 'slashed', 'withdrawn', 'expired')),
    
    -- Reason/message for vouching (public endorsement)
    endorsement_message TEXT 
        CHECK (endorsement_message IS NULL OR length(endorsement_message) <= 500),
    
    -- On-chain transaction references
    stake_tx_hash TEXT NOT NULL,
    release_tx_hash TEXT,
    slash_tx_hash TEXT,
    
    -- Block information
    block_number INTEGER,
    block_timestamp TEXT,
    
    -- Reward tracking (if campaign succeeds)
    reward_earned TEXT DEFAULT '0',
    reward_claimed TEXT DEFAULT '0',
    reward_claimed_at TEXT,
    
    -- Slash tracking (if vouched for failed/fraudulent campaign)
    slash_amount TEXT DEFAULT '0',
    slash_reason TEXT,
    slashed_at TEXT,
    
    -- Expiry (optional time-limited vouching)
    expires_at TEXT,
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    vouched_at TEXT NOT NULL DEFAULT (datetime('now')),
    released_at TEXT,
    withdrawn_at TEXT,
    
    -- Unique constraint: One voucher stake per campaign per address
    UNIQUE (campaign_id, voucher_address),
    
    -- Foreign key constraints
    FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
    FOREIGN KEY (voucher_address) REFERENCES users(address) ON DELETE RESTRICT
);

-- ============================================================================
-- INDEXES
-- Purpose: Optimize query performance for common access patterns
-- ============================================================================

-- Primary access patterns
CREATE INDEX IF NOT EXISTS idx_vouchers_campaign ON vouchers(campaign_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_address ON vouchers(voucher_address);
CREATE INDEX IF NOT EXISTS idx_vouchers_status ON vouchers(status);

-- Transaction lookup
CREATE INDEX IF NOT EXISTS idx_vouchers_tx_hash ON vouchers(stake_tx_hash);

-- Date-based queries
CREATE INDEX IF NOT EXISTS idx_vouchers_vouched_at ON vouchers(vouched_at DESC);

-- Composite: Campaign + Status for campaign stats
CREATE INDEX IF NOT EXISTS idx_vouchers_campaign_status ON vouchers(campaign_id, status);

-- Composite: Voucher address + Status for user dashboards
CREATE INDEX IF NOT EXISTS idx_vouchers_address_status ON vouchers(voucher_address, status);

-- Active vouchers for a campaign
CREATE INDEX IF NOT EXISTS idx_vouchers_campaign_active ON vouchers(campaign_id, amount) 
    WHERE status = 'active';

-- Expiring vouchers query
CREATE INDEX IF NOT EXISTS idx_vouchers_expires ON vouchers(expires_at) 
    WHERE expires_at IS NOT NULL AND status = 'active';

-- ============================================================================
-- TRIGGERS
-- Purpose: Maintain data integrity and audit trail
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS trg_vouchers_updated_at
AFTER UPDATE ON vouchers
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE vouchers SET updated_at = datetime('now') WHERE voucher_id = NEW.voucher_id;
END;

-- Update campaign voucher count on new voucher
CREATE TRIGGER IF NOT EXISTS trg_vouchers_increment_count
AFTER INSERT ON vouchers
FOR EACH ROW
WHEN NEW.status = 'active'
BEGIN
    UPDATE campaigns 
    SET 
        voucher_count = voucher_count + 1,
        updated_at = datetime('now')
    WHERE campaign_id = NEW.campaign_id;
END;
