-- Migration: 0006_disputers_domain
-- Created: 2025-01-29
-- Description: Disputers domain schema - Challenge mechanism for campaigns
-- Domain: Disputers

-- ============================================================================
-- DISPUTERS TABLE
-- Purpose: Tracks users who stake funds to dispute/challenge a campaign
-- Design: Challenge mechanism with stake-to-dispute model
-- ============================================================================
CREATE TABLE IF NOT EXISTS disputers (
    -- Primary key: UUID generated by application layer
    disputer_id TEXT PRIMARY KEY 
        CHECK (length(disputer_id) = 36),
    
    -- Foreign key to campaign
    campaign_id TEXT NOT NULL,
    
    -- Disputer's wallet address (foreign key to users)
    disputer_address TEXT NOT NULL,
    
    -- Staked amount for dispute (in wei, stored as TEXT for large numbers)
    amount TEXT NOT NULL 
        CHECK (CAST(amount AS INTEGER) > 0),
    
    -- Dispute status
    status TEXT NOT NULL DEFAULT 'pending' 
        CHECK (status IN ('pending', 'active', 'upheld', 'rejected', 'withdrawn', 'expired')),
    
    -- Dispute reason (required)
    reason TEXT NOT NULL 
        CHECK (length(reason) >= 10 AND length(reason) <= 2000),
    
    -- Dispute category/type
    dispute_type TEXT NOT NULL DEFAULT 'general' 
        CHECK (dispute_type IN ('fraud', 'misrepresentation', 'rule_violation', 'verification_failure', 'general')),
    
    -- Evidence supporting the dispute (JSON array of evidence items)
    evidence TEXT DEFAULT '[]',
    
    -- On-chain transaction references
    stake_tx_hash TEXT NOT NULL,
    resolution_tx_hash TEXT,
    
    -- Block information
    block_number INTEGER,
    block_timestamp TEXT,
    
    -- Resolution details
    resolution_outcome TEXT 
        CHECK (resolution_outcome IS NULL OR resolution_outcome IN ('upheld', 'rejected', 'partial')),
    resolution_notes TEXT,
    resolved_by TEXT,  -- Address of resolver (admin/verifier/consensus)
    resolved_at TEXT,
    
    -- Reward/penalty tracking
    reward_earned TEXT DEFAULT '0',  -- If dispute upheld
    stake_returned TEXT DEFAULT '0',
    stake_slashed TEXT DEFAULT '0',  -- If dispute rejected
    
    -- Expiry (disputes must be resolved within timeframe)
    expires_at TEXT,
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    disputed_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Unique constraint: One dispute per campaign per address
    UNIQUE (campaign_id, disputer_address),
    
    -- Foreign key constraints
    FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE RESTRICT,
    FOREIGN KEY (disputer_address) REFERENCES users(address) ON DELETE RESTRICT
);

-- ============================================================================
-- INDEXES
-- Purpose: Optimize query performance for common access patterns
-- ============================================================================

-- Primary access patterns
CREATE INDEX IF NOT EXISTS idx_disputers_campaign ON disputers(campaign_id);
CREATE INDEX IF NOT EXISTS idx_disputers_address ON disputers(disputer_address);
CREATE INDEX IF NOT EXISTS idx_disputers_status ON disputers(status);

-- Dispute type filtering
CREATE INDEX IF NOT EXISTS idx_disputers_type ON disputers(dispute_type);

-- Transaction lookup
CREATE INDEX IF NOT EXISTS idx_disputers_tx_hash ON disputers(stake_tx_hash);

-- Date-based queries
CREATE INDEX IF NOT EXISTS idx_disputers_disputed_at ON disputers(disputed_at DESC);
CREATE INDEX IF NOT EXISTS idx_disputers_resolved_at ON disputers(resolved_at DESC);

-- Composite: Campaign + Status for campaign stats
CREATE INDEX IF NOT EXISTS idx_disputers_campaign_status ON disputers(campaign_id, status);

-- Composite: Disputer address + Status for user dashboards
CREATE INDEX IF NOT EXISTS idx_disputers_address_status ON disputers(disputer_address, status);

-- Active/pending disputes requiring resolution
CREATE INDEX IF NOT EXISTS idx_disputers_pending ON disputers(status, created_at) 
    WHERE status IN ('pending', 'active');

-- Expiring disputes query
CREATE INDEX IF NOT EXISTS idx_disputers_expires ON disputers(expires_at) 
    WHERE expires_at IS NOT NULL AND status IN ('pending', 'active');

-- ============================================================================
-- TRIGGERS
-- Purpose: Maintain data integrity and audit trail
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS trg_disputers_updated_at
AFTER UPDATE ON disputers
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE disputers SET updated_at = datetime('now') WHERE disputer_id = NEW.disputer_id;
END;

-- Update campaign disputer count and flag on new dispute
CREATE TRIGGER IF NOT EXISTS trg_disputers_increment_count
AFTER INSERT ON disputers
FOR EACH ROW
WHEN NEW.status IN ('pending', 'active')
BEGIN
    UPDATE campaigns 
    SET 
        disputer_count = disputer_count + 1,
        is_disputed = 1,
        updated_at = datetime('now')
    WHERE campaign_id = NEW.campaign_id;
END;

-- Update campaign disputed flag when all disputes resolved
CREATE TRIGGER IF NOT EXISTS trg_disputers_check_resolved
AFTER UPDATE OF status ON disputers
FOR EACH ROW
WHEN NEW.status IN ('upheld', 'rejected', 'withdrawn', 'expired')
BEGIN
    UPDATE campaigns 
    SET 
        is_disputed = (
            SELECT COUNT(*) > 0 
            FROM disputers 
            WHERE campaign_id = NEW.campaign_id 
            AND status IN ('pending', 'active')
        ),
        updated_at = datetime('now')
    WHERE campaign_id = NEW.campaign_id;
END;
