-- Migration: 0008_consensus_audit
-- Created: 2025-01-29
-- Description: Consensus results and audit trail tables
-- Domain: Consensus & Audit Logging

-- ============================================================================
-- CONSENSUS_RESULTS TABLE
-- Purpose: Detailed storage for CRE/DECO AI consensus verification results
-- Design: Separate table for large consensus logs (normalized from campaigns)
-- ============================================================================
CREATE TABLE IF NOT EXISTS consensus_results (
    -- Primary key: UUID generated by application layer
    result_id TEXT PRIMARY KEY 
        CHECK (length(result_id) = 36),
    
    -- Foreign key to campaign
    campaign_id TEXT NOT NULL,
    
    -- Consensus round/attempt number
    round_number INTEGER NOT NULL DEFAULT 1,
    
    -- AI provider that performed verification
    ai_provider TEXT NOT NULL 
        CHECK (length(ai_provider) >= 1 AND length(ai_provider) <= 50),
    
    -- Provider model version
    model_version TEXT,
    
    -- Verification result
    result INTEGER NOT NULL,  -- 1 = true/pass, 0 = false/fail
    
    -- Confidence score (0.0 to 1.0)
    confidence REAL 
        CHECK (confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)),
    
    -- Detailed reasoning from AI
    reasoning TEXT 
        CHECK (length(reasoning) <= 5000),
    
    -- Sources used for verification (JSON array)
    sources TEXT DEFAULT '[]',
    
    -- Raw API response (for debugging/audit)
    raw_response TEXT,
    
    -- Verification type
    verification_type TEXT NOT NULL DEFAULT 'baseline' 
        CHECK (verification_type IN ('baseline', 'progress', 'completion', 'dispute')),
    
    -- Processing metadata
    processing_time_ms INTEGER,
    tokens_used INTEGER,
    cost_estimate TEXT,
    
    -- Hash of the input data used (for reproducibility)
    input_hash TEXT,
    
    -- IPFS CID for permanent storage (optional)
    ipfs_cid TEXT,
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    verified_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Foreign key constraints
    FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE CASCADE
);

-- ============================================================================
-- AUDIT_LOG TABLE
-- Purpose: Comprehensive audit trail for all system actions
-- Design: Immutable append-only log for compliance and debugging
-- ============================================================================
CREATE TABLE IF NOT EXISTS audit_log (
    -- Primary key: Auto-incrementing for guaranteed ordering
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    
    -- Actor who performed the action
    actor_address TEXT,  -- NULL for system actions
    actor_type TEXT NOT NULL DEFAULT 'user' 
        CHECK (actor_type IN ('user', 'admin', 'verifier', 'system', 'contract')),
    
    -- Action performed
    action TEXT NOT NULL 
        CHECK (length(action) >= 1 AND length(action) <= 100),
    action_category TEXT NOT NULL DEFAULT 'general' 
        CHECK (action_category IN ('auth', 'campaign', 'pledge', 'vouch', 'dispute', 'consensus', 'admin', 'system', 'general')),
    
    -- Target entity
    entity_type TEXT 
        CHECK (entity_type IN ('user', 'campaign', 'pledge', 'voucher', 'disputer', 'category', 'tag', 'system')),
    entity_id TEXT,
    
    -- Action details (JSON)
    details TEXT DEFAULT '{}',
    
    -- Previous state (for change tracking)
    previous_state TEXT,
    
    -- New state (for change tracking)
    new_state TEXT,
    
    -- Request metadata
    ip_address TEXT,
    user_agent TEXT,
    request_id TEXT,
    
    -- On-chain reference (if applicable)
    tx_hash TEXT,
    block_number INTEGER,
    
    -- Status of the action
    status TEXT DEFAULT 'success' 
        CHECK (status IN ('success', 'failure', 'pending')),
    error_message TEXT,
    
    -- Timestamp (immutable)
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================================
-- CAMPAIGN_HISTORY TABLE
-- Purpose: Detailed campaign state history (extracted from campaigns.history JSONB)
-- Design: Normalized history for complex queries
-- ============================================================================
CREATE TABLE IF NOT EXISTS campaign_history (
    -- Primary key: Auto-incrementing
    history_id INTEGER PRIMARY KEY AUTOINCREMENT,
    
    -- Foreign key to campaign
    campaign_id TEXT NOT NULL,
    
    -- Action performed
    action TEXT NOT NULL 
        CHECK (length(action) >= 1 AND length(action) <= 100),
    
    -- Actor who performed the action
    actor_address TEXT,
    actor_type TEXT DEFAULT 'user',
    
    -- State change details
    from_status TEXT,
    to_status TEXT,
    
    -- Additional details (JSON)
    details TEXT DEFAULT '{}',
    
    -- On-chain reference (if applicable)
    tx_hash TEXT,
    
    -- Timestamp
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Foreign key constraints
    FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE CASCADE
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Consensus results indexes
CREATE INDEX IF NOT EXISTS idx_consensus_campaign ON consensus_results(campaign_id);
CREATE INDEX IF NOT EXISTS idx_consensus_provider ON consensus_results(ai_provider);
CREATE INDEX IF NOT EXISTS idx_consensus_type ON consensus_results(verification_type);
CREATE INDEX IF NOT EXISTS idx_consensus_result ON consensus_results(result);
CREATE INDEX IF NOT EXISTS idx_consensus_created ON consensus_results(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consensus_campaign_round ON consensus_results(campaign_id, round_number);

-- Audit log indexes (optimized for common queries)
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor_address);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_category ON audit_log(action_category);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_status ON audit_log(status);
CREATE INDEX IF NOT EXISTS idx_audit_tx ON audit_log(tx_hash) WHERE tx_hash IS NOT NULL;

-- Campaign history indexes
CREATE INDEX IF NOT EXISTS idx_history_campaign ON campaign_history(campaign_id);
CREATE INDEX IF NOT EXISTS idx_history_action ON campaign_history(action);
CREATE INDEX IF NOT EXISTS idx_history_actor ON campaign_history(actor_address);
CREATE INDEX IF NOT EXISTS idx_history_created ON campaign_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_history_status_change ON campaign_history(campaign_id, from_status, to_status);

-- ============================================================================
-- NOTE: No UPDATE triggers on audit_log - it should be append-only
-- ============================================================================
