-- Migration: 0009_sessions_notifications
-- Created: 2025-01-29
-- Description: User sessions and notifications tables
-- Domain: Sessions & Notifications

-- ============================================================================
-- SESSIONS TABLE
-- Purpose: Track user authentication sessions (wallet-based)
-- Design: Support for SIWE (Sign-In with Ethereum) sessions
-- ============================================================================
CREATE TABLE IF NOT EXISTS sessions (
    -- Primary key: Session token (secure random string)
    session_id TEXT PRIMARY KEY 
        CHECK (length(session_id) >= 32),
    
    -- User wallet address
    user_address TEXT NOT NULL,
    
    -- SIWE message and signature for verification
    siwe_message TEXT,
    siwe_signature TEXT,
    siwe_nonce TEXT,
    
    -- Session metadata
    chain_id INTEGER,
    issued_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    
    -- Device/client information
    ip_address TEXT,
    user_agent TEXT,
    device_fingerprint TEXT,
    
    -- Session status
    is_valid INTEGER DEFAULT 1,
    revoked_at TEXT,
    revoke_reason TEXT,
    
    -- Last activity tracking
    last_activity_at TEXT DEFAULT (datetime('now')),
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Foreign key constraints
    FOREIGN KEY (user_address) REFERENCES users(address) ON DELETE CASCADE
);

-- ============================================================================
-- NOTIFICATIONS TABLE
-- Purpose: Store user notifications for campaigns, pledges, etc.
-- Design: Flexible notification system with read/dismiss tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS notifications (
    -- Primary key: UUID generated by application layer
    notification_id TEXT PRIMARY KEY 
        CHECK (length(notification_id) = 36),
    
    -- Recipient user address
    recipient_address TEXT NOT NULL,
    
    -- Notification type
    type TEXT NOT NULL 
        CHECK (type IN (
            'campaign_created', 'campaign_approved', 'campaign_active', 
            'campaign_completed', 'campaign_failed', 'campaign_disputed',
            'pledge_received', 'pledge_released', 'pledge_refunded',
            'vouch_received', 'vouch_slashed',
            'dispute_filed', 'dispute_resolved',
            'consensus_result', 'yield_available',
            'system', 'announcement'
        )),
    
    -- Notification content
    title TEXT NOT NULL 
        CHECK (length(title) >= 1 AND length(title) <= 200),
    message TEXT NOT NULL 
        CHECK (length(message) >= 1 AND length(message) <= 1000),
    
    -- Related entity (optional)
    entity_type TEXT 
        CHECK (entity_type IN ('campaign', 'pledge', 'voucher', 'disputer', 'user', 'system')),
    entity_id TEXT,
    
    -- Action link (optional)
    action_url TEXT,
    action_label TEXT,
    
    -- Notification priority
    priority TEXT DEFAULT 'normal' 
        CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    
    -- Read/dismiss status
    is_read INTEGER DEFAULT 0,
    read_at TEXT,
    is_dismissed INTEGER DEFAULT 0,
    dismissed_at TEXT,
    
    -- Email notification status (if applicable)
    email_sent INTEGER DEFAULT 0,
    email_sent_at TEXT,
    
    -- Push notification status (if applicable)
    push_sent INTEGER DEFAULT 0,
    push_sent_at TEXT,
    
    -- Expiry (optional - some notifications expire)
    expires_at TEXT,
    
    -- Metadata (JSON)
    metadata TEXT DEFAULT '{}',
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Foreign key constraints
    FOREIGN KEY (recipient_address) REFERENCES users(address) ON DELETE CASCADE
);

-- ============================================================================
-- NOTIFICATION_PREFERENCES TABLE
-- Purpose: User-specific notification settings
-- Design: Granular control over notification channels and types
-- ============================================================================
CREATE TABLE IF NOT EXISTS notification_preferences (
    -- Foreign key to user
    user_address TEXT PRIMARY KEY,
    
    -- Global settings
    notifications_enabled INTEGER DEFAULT 1,
    email_enabled INTEGER DEFAULT 1,
    push_enabled INTEGER DEFAULT 1,
    
    -- Per-type settings (JSON object)
    type_settings TEXT DEFAULT '{}',
    
    -- Quiet hours (optional)
    quiet_hours_enabled INTEGER DEFAULT 0,
    quiet_hours_start TEXT,  -- HH:MM format
    quiet_hours_end TEXT,    -- HH:MM format
    quiet_hours_timezone TEXT DEFAULT 'UTC',
    
    -- Digest preferences
    digest_enabled INTEGER DEFAULT 0,
    digest_frequency TEXT DEFAULT 'daily' 
        CHECK (digest_frequency IN ('daily', 'weekly', 'monthly')),
    
    -- Audit columns
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    -- Foreign key constraints
    FOREIGN KEY (user_address) REFERENCES users(address) ON DELETE CASCADE
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Sessions indexes
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_address);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_valid ON sessions(is_valid, expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_activity ON sessions(last_activity_at DESC);

-- Notifications indexes
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_address);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_entity ON notifications(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(recipient_address, is_read) 
    WHERE is_read = 0;
CREATE INDEX IF NOT EXISTS idx_notifications_priority ON notifications(priority, created_at DESC) 
    WHERE is_dismissed = 0;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update notification preferences updated_at
CREATE TRIGGER IF NOT EXISTS trg_notification_prefs_updated_at
AFTER UPDATE ON notification_preferences
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE notification_preferences SET updated_at = datetime('now') WHERE user_address = NEW.user_address;
END;

-- Update user last_login_at on session creation
CREATE TRIGGER IF NOT EXISTS trg_sessions_user_login
AFTER INSERT ON sessions
FOR EACH ROW
BEGIN
    UPDATE users 
    SET last_login_at = datetime('now'), updated_at = datetime('now')
    WHERE address = NEW.user_address;
END;
